version: "3"
services:
  redis:
    image: library/redis:7-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template_development
