name: Build and Release Image

on:
  push:
    branches:
      - master
      - main
    tags:
      - "**"
  schedule:
    # Run at 1AM (5AM UTC)
    - cron:  '0 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Custom suffix for tag'
        required: false

  # Allows you to use the GitHub API to trigger a webhook event
  repository_dispatch:

jobs:
  build:
    uses: ibm-skills-network/.github/.github/workflows/release.yml@main
    with:
      image: icr.io/skills-network-faculty/rails-app-template
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_PASSWORD: ${{ secrets.ICR_PASSWORD }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
